Глава 4. Сортировки

4.1.1. Пусть a[1],...,a[n] — целые числа. 
Требуется построить массив b[1],...,b[n], содержащий те же числа, для которого b[1]<,...,<b[n].

In [ ]:
arr = [8,12,5,6,1,9,3,8,1]

def bubble_sort(a):
    for i in reversed(range(len(a))):
        for j in range(1, i + 1):
            if a[j-1] > a[j]:
                a[j], a[j-1] = a[j-1], a[j]
            print(a)
        print()
print(arr)                
bubble_sort(arr)

## Алгоритмы порядка nlogn

4.2.1. Сортировка слиянием

In [2]:
import numpy as np

In [3]:
def merge(a,b):
    c = np.empty((a.size+b.size),dtype=int)
    i,j = 0,0
    while i<a.size and j<b.size:
        if a[i]<b[j]:
            c[i+j]=a[i]
            i+=1
        else:
            c[i+j]=b[j]
            j+=1 
            
    while i<len(a):
        c[i+j]=a[i]
        i+=1
    while j<len(b):
        c[i+j]=b[j]
        j+=1
    return c

merge(
    np.array([1,4,6,9]), 
    np.array([2,3,4,4,6,7,10])
)

array([ 1,  2,  3,  4,  4,  4,  6,  6,  7,  9, 10])

In [6]:
def smart_merge(A,s1,e1,e2):
    B = np.copy(A[s1:e1+1])
    i = 0
    j = e1+1
    while i<B.size and j<e2:
        print(i,j)
        if B[i]<A[j]:
            A[s1+i]=B[i]
            i+=1
        else:
            A[s1+i]=A[j]
            j+=1
            s1+=1
        print(A)
    
    print(i,j)
    while i<b.size:
        A[s1+i]=B[i]
        i+=1
        
    while j<e2:
        A[s1+i]=A[j]
        j+=1
        

A = np.array([1,3,2,4])
smart_merge(A,0,1,3)
print(A)

0 2
[1 3 2 4]
1 2
[1 2 2 4]
1 3


NameError: name 'b' is not defined

In [150]:
def merge_sort(A,begin,end):
    mid = (begin+end) // 2
    print(begin,end,A[begin:end+1])
    if end-begin<2: 
        #return A[begin:end+1]
        pass
    else: 
        merge_sort(A,begin,mid)
        merge_sort(A,mid+1,end)
        return smart_merge(A,begin,mid,end)
        

A = np.array([12,6,8,4,9,2,6,1])
begin=0
end=A.size-1
merge_sort(A, begin, end)

0 7 [12  6  8  4  9  2  6  1]
0 3 [12  6  8  4]
0 1 [12  6]
2 3 [8 4]


IndexError: index 2 is out of bounds for axis 0 with size 2

In [144]:
def merge_sort(A,begin,end):
    mid = (begin+end) // 2
    print(begin,mid,end)
    if end==begin: 
        return A[begin:end+1]
    else: 
        return merge(
            merge_sort(A,begin,mid),
            merge_sort(A,mid+1,end)
        )
        
A = np.array([12,6,8,4,9,2,6,1])
merge_sort(A, 0, A.size-1)

0 3 7
0 1 3
0 0 1
0 0 0
1 1 1
2 2 3
2 2 2
3 3 3
4 5 7
4 4 5
4 4 4
5 5 5
6 6 7
6 6 6
7 7 7


array([ 1,  2,  4,  6,  6,  8,  9, 12])

In [137]:
def bottom_up_merge_sort(A):
    k=2
    while k/2<=A.size:
        for i in range(0,A.size,k):
            print(A[i:i+k/2],end=",")
            print(A[i+k/2:i+k],end="; ")
            A[i:i+k] = merge(A[i:i+k/2],A[i+k/2:i+k])
            #smart_merge(A,i,i+k/2,i+k)
                
        print()
        k*=2
            
A = np.array([12,6,8,4,9,2,6,1,3,7])
bottom_up_merge_sort(A) 
print(A)

[12],[6]; [8],[4]; [9],[2]; [6],[1]; [3],[7]; 
[ 6 12],[4 8]; [2 9],[1 6]; [3 7],[]; 
[ 4  6  8 12],[1 2 6 9]; [3 7],[]; 
[ 1  2  4  6  6  8  9 12],[3 7]; 
[ 1  2  3  4  6  6  7  8  9 12]


/Users/aleksei-mac1/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:5: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/aleksei-mac1/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:6: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/aleksei-mac1/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:7: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


4.2.1. Сортировка деревом

In [ ]:
def max_heapify(arr,start,end):
    root=start
    child = 2*root+1
    if child<=end:
        if child+1<=end and arr[child]<arr[child+1]: 
            child+=1
        if arr[root]<arr[child]: 
                arr[child],arr[root]=arr[root],arr[child]         
                max_heapify(arr,child,end)

In [ ]:
def build_max_heap(arr):
    end=len(arr)-1
    for i in reversed(range(0,len(arr))):
        print(i)
        max_heapify(arr,i,end)

In [ ]:
def heap_sort(arr):
    build_max_heap(arr)
    for end in reversed(range(0,len(arr))):
        arr[end],arr[0]=arr[0],arr[end]
        max_heapify(arr,0,end-1)

In [ ]:
arr = [16,4,10,14,7,9,3,2,8,1]
max_heapify(arr,1,end=len(arr)-1)
print(arr)

In [ ]:
arr = [4,1,2,3,2,16,9,10,14,8,7]
heapsort(arr)

print(arr)