"Программирование: теоремы и задачи" by А. Шень.
==

In [1]:
import numpy as np

1. Переменные, выражения, присваивания.
--

1.1.1-1.1.2 Даны две целые переменные a, b. Составить фрагмент программы,
после исполнения которого значения переменных поменялись бы местами.

In [2]:
a = 12
b = 13

t = a
a = b
b = t
print(a,b)

13 12


In [3]:
# python way
a,b = b,a
print(a,b)

12 13


In [4]:
# без доп. переменных
a = a + b 
b = a - b # == a
a = a - b # == b 
print(a,b)

13 12


1.1.3-1.1.4 Дано целое число а и натуральное число n. Вычислить a^n.

In [5]:
a = 2
n = 7

b = 1
for k in range(1,n+1):
   b = b*a
print(b)

128


In [6]:
2 % 2

0

In [7]:
# за C*log(n) действий
a = 2
n = 7

k = n
b = 1
c = a

print('{}^{} =={}*{}^{}'.format(a,n,b,c,k))
while k != 0:
    if n % 2 == 0:
        c = c * c
        k = k / 2
    else:
        b = b * c
        k = k - 1
    print('{}^{} =={}*{}^{}'.format(a,n,b,c,k))

2^7 ==1*2^7
2^7 ==2*2^6
2^7 ==4*2^5
2^7 ==8*2^4
2^7 ==16*2^3
2^7 ==32*2^2
2^7 ==64*2^1
2^7 ==128*2^0


1.1.7. Дано натуральное число а и целое положительное число d. Вычислить частное q и остаток r при делении а на d, не используя операций div и mod.

In [8]:
# a = q*d + r
a = 17
d = 5

q = 0
r = a
while r >= d:
    r = r - d
    q = q + 1

print('{} =={}*{}+{}'.format(a,q,d,r)) 

17 ==3*5+2


1.1.8. Дано натуральное n, вычислить n! (0! = 1, n! = n · (n − 1)!).

In [9]:
def fac(n):
    n = 5
    r = 1
    while n != 0:
        r = r * n
        n = n - 1
    return r

print(fac(4))

120


1.1.9 - 1.1.10 Последовательность Фибоначчи определяется так: a0 = 0, a1 =
1, ak = ak-1 + ak-2 при k2. Дано n, вычислить an.

In [10]:
def fib(n):
    k = 2 
    a = [0,1]
    while k <= n:
        a.append( a[k-1] + a[k-2] )
        k += 1
    return a[n]

for i in range(0,9):
    print(fib(i))

0
1
1
2
3
5
8
13
21


In [11]:
# за C*log(n) матричных умножений
def matrix_fib(n):
    a = np.matrix('1 1; 1 0')
    k = n
    b = np.matrix('1 0; 0 1')
    c = a
    while k != 0:
        if n % 2 == 0:
            c = c * c
            k = k / 2
        else:
            b = b * c
            k = k - 1

    return b

a = np.matrix('1 1; 1 0')
n = 7
print(a)
print(matrix_fib(n))

[[1 1]
 [1 0]]
[[21 13]
 [13  8]]


1.1.11 - 1.1.12 Дано натуральное n, вычислить Sum{ 1/i! } i = 0..n

In [12]:
def smart_series_sum(n):
    k = 0 
    last = 1
    result = last
    while k < n:
        k += 1
        last = last/k
        result += last    
    return result

print(smart_series_sum(4))

2.708333333333333


1.1.20-1.1.21. Составить программу, печатающую квадраты всех натуральных чисел от 0 до заданного натурального n. Использовать из арифметических операций лишь сложение и вычитание, причем общее число действий дол- жно быть порядка n.

In [13]:
# (k-1)^2 = k^2-2k+1 => k^2 = (k-1)^2+2k-1

def print_squares(n):
    k   = 0
    k_2 = 0
    print(k_2)
    while k != n: 
        k += 1
        k_2 = k_2 + k+k - 1
        print(k_2)

print_squares(5)

0
1
4
9
16
25


1.1.22. Составить программу, печатающую разложение на простые множители заданного натурального числа n > 0.

In [14]:
def prime_factorization(n):
    k = 2
    i = 1
    lasting = n
    while k != n:
        if lasting % k == 0:
            print(k)
            lasting = lasting / k
        else:
            k = k+1
        i+=1
    print('{} operations'.format(i))

prime_factorization((17*2*5*7*9*13))         

2
3
3
5
7
13
17
139236 operations


In [15]:
print(np.sqrt(17))

4.12310562562


In [16]:
def smart_prime_factorization(n):
    k = 2
    i = 1
    lasting = n
    while k*k < n:
        if lasting % k == 0:
            print(k)
            lasting = lasting / k
        else:
            k = k+1
        i += 1
    print('{} operations'.format(i))

smart_prime_factorization((17*2*5*7*9*13))  

2
3
3
5
7
13
17
380 operations


1.1.26. Составить программу, печатающую десятичную запись заданного натурального числа n > 0. 

In [17]:
def numbers(n):
    base = 1
    while 10*base < n:
        base = base * 10
    while base > 1:
        print(int(n // base))
        n = n % base
        base /= 10
    print(int(n))
        
numbers(1234)

1
2
3
4


1.1.28. Дано натуральное n. Подсчитать количество решений неравенства x^2 + y^2 < n в натуральных числах, не используя действий с вещественными числами.

In [ ]:
def solutions(n):
    x = 0
    y = 0
    

1.1.32. Дана функция f: {1...N} → {1...N}. Найти период последовательности 1,f(1),f(f(1),... Количество действий должно быть пропорционально суммарной длине предпериода и периода (эта сумма может быть существенно меньше N).

In [ ]:
periodic_func_1 = lambda k: 1 + k % 17

In [ ]:
def cycle(n,f):
    result = 1
    for i in range(1,n):
        result = f(result)
    return result

In [ ]:
for i in range(1,36):
    print(cycle(i,periodic_func_1))

In [ ]:
def find_period(f):
    k = 1
    a = f(1)
    b = f(f(1))
    while a!=b:
        k+=1
        a = f(a)
        b = f(f(b))
    
    l = 1
    b = f(a) # k+1 шаг
    while a!=b:
        l = l+1
        b = f(b)
    
    return l
    
    

find_period(periodic_func)

## 2. Массивы

1.2.5. Дан массив x: array[1..n] of integer, причем x[1]<=x[2]<=...<=x[n] Найти количество различных чисел среди элементов этого массива.

In [18]:
array = [1,1,1,2,2,3,3,4,4,5,5,5,5,5]
n = len(array)

def uniq(arr,n):
    uniq_number = 1
    for i in range(1,n):
        print(arr[i-1] != arr[i])
        if arr[i-1] != arr[i]:
            uniq_number+=1
    return uniq_number

print(uniq(array,n))
    

False
False
True
False
True
False
True
False
True
False
False
False
False
5


1.2.6. Прямоугольное поле m×n разбито на mn квадратных клеток. Некоторые клетки покрашены в чёрный цвет. Известно, что все чёрные клетки могут быть разбиты на несколько непересекающихся и не имеющих общих вершин чёрных прямоугольников. Подсчитать число чёрных прямоугольников, о которых шла речь. Число действий должно быть порядка mn.

In [24]:
random_field = np.matrix(
    '1 1 0 0; 0 0 1 1; 1 1 0 0'
)
print(random_field)

[[1 1 0 0]
 [0 0 1 1]
 [1 1 0 0]]


In [25]:
def count_black_rectangles(a):
    def is_left_corner(m,i,j):
        if a[i,j]==1:
            if i==0:
                if j==0:
                    return True
                else:
                    if a[i,j-1]==1:
                        return False
                    else:
                        return True
            else:
                if j==0:
                    if a[i-1,j]==1:
                        return False
                    else:
                        return True
                else:
                    if a[i-1,j]==1 or a[i,j-1]==1:
                        return False
                    else:
                        return True       
        else:
            return False
        
    n,m = a.shape
    
    recnum = 0
    for i in range(0,n):
        for j in range(0,m):
            if is_left_corner(a,i,j):
                recnum +=1
    return recnum
    
    
count_black_rectangles(random_field)

3

1.2.7 - 1.2.8. Дан массив x: array[1..n] of integer. Найти количество различных чисел среди элементов этого массива.

In [41]:
array = [1,1,1,2,2,3,3,4,4,5,5,5,5,5]
n = len(array)

# O(n^2)
def count_uniq(array):
    set_     = [array[0]]
    set_size = 1
    
    for i in range(1,n):
        elem = array[i]
        precence = False
        for j in range(0,set_size):
            precence = precence or (set_[j] == elem)
        if not precence:
            set_.append(elem)
            set_size+=1
        
    return set_,set_size
   
print(count_uniq(array))

([1, 2, 3, 4, 5], 5)


In [ ]:
# O(nlogn)
# 1. sort
# 2. линейный проход

1.2.9. Та же задача, если известно, что все элементы массива — числа от 1 до k и число действий должно быть порядка n + k.

1.2.10. Дан массив x[1]..x[n] целых чисел. Не используя других массивов, переставить элементы массива в обратном порядке.

In [11]:
array = [1,2,3,4,5,6,7,8,9,10,11,12]
n = len(array)

for i in range(0, n // 2):
    tmp = array[i]
    array[i]=array[n-1-i]
    array[n-1-i]=tmp
    
print(array)

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


1.2.11.Дан массив целых чисел x[1]..x[m+n], рассматриваемый как соединение двух его отрезков: начала x[1]..x[m] длины m и конца x[m+1]..x[m+n] длины n. Не используя дополнительных массивов, переставить начало и конец. 

In [ ]:
array = [1,2,3,4,5,6,7,8,9,10,11]

#result = [8,9,10,11,1,2,3,4,5,6,7]
n = len(array)
m = 4

for i in range(0, m // 2):
    #print(i)
    tmp = array[i]
    array[i]=array[m-1-i]
    array[m-1-i]=tmp
    
#print(array)

for i in range(m, m + n // 2):
    print(i)
    #print(m+n-1-i)
    #tmp = array[i]
    #array[i]=array[m+n-1-i]
    #array[m+n-1-i]=tmp

#print(array)


1.2.16.  Даны  два  возрастающих массива x: array [1..k] of integer и y: array [1..l] of  integer. Найти  количество  общих элементов в этих массивах (количество тех целых t, для которых t=x[i]=y[j] для некоторых i и j). (Число действий порядка k+l.)

In [65]:
def count_common(x,y):
    xpos=0
    ypos=0
    count=0
    
    while xpos<len(x) and ypos<len(y):
        if x[xpos]==y[ypos]:
            xpos+=1
            ypos+=1
            count+=1
        elif x[xpos]<y[ypos]:
            xpos+=1
        elif x[xpos]>y[ypos]:
            ypos+=1
       
    print(xpos,ypos)
    return count


x = [2,3,4,6,7,8,9,10,11,16]
y = [1,2,4,5,8,9,10,12,16]
count_common(x,y)

10 9


6

1.2.17. Решить предыдущую задачу, если известно лишь, что:
x[1] <= ... <= x[k] и y[1] <= ... <= y[l]

In [73]:
def count_common(x,y):
    xpos=0
    ypos=0
    count=0
    
    while xpos<len(x) and ypos<len(y):
        if x[xpos]==y[ypos]:
            count+=1
            current=x[xpos]
            while xpos<len(x) and x[xpos]==current:
                xpos+=1
            while ypos<len(y) and y[ypos]==current:
                ypos+=1
        elif x[xpos]<y[ypos]:
            xpos+=1
        elif x[xpos]>y[ypos]:
            ypos+=1
       
    print(xpos,ypos)
    return count


x = [2,2,3,4,6,6,7,8,9,9,10,10,11,16]
y = [1,2,4,4,5,8,9,9,9,10,12,16,16]
count_common(x,y)

14 13


6

1.2.19.Даны два массива x[1]<=...<=x[k] и y[1]<=...<=y[l]. "Соединить" их в массив z[1]<=...<=z[m] Число действий
порядка m.

In [81]:
def merge(x,y):
    result = []
    xpos=0
    ypos=0
    while xpos<len(x) and ypos<len(y):
        if x[xpos]<y[ypos]:
            result.append(x[xpos])
            xpos+=1
        elif x[xpos]>y[ypos]:  
            result.append(y[ypos])
            ypos+=1
        else:
            result.append(x[xpos])
            result.append(y[ypos])
            xpos+=1
            ypos+=1
            
    while xpos<len(x):
        result.append(x[xpos])
        xpos+=1
    while ypos<len(y):
        result.append(y[ypos])
        ypos+=1
    return result

x = [2,2,3,4,6,6,7,8,9,9,10,10,11,16,16,17,21,24]
y = [1,2,4,4,5,8,9,9,9,10,12,16,16]
merge(x,y)

[1,
 2,
 2,
 2,
 3,
 4,
 4,
 4,
 5,
 6,
 6,
 7,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 11,
 12,
 16,
 16,
 16,
 16,
 17,
 21,
 24]

1.2.20. Даны два массива x[1]<=...<=x[k] и y[1]<=...<=y[l]. Найти  их  "пересечение", т.е.массив z[1]<=...<=z[m], содержащий их общие  элементы,  причем  кратность  каждого элемента в массиве z равняется минимуму из его кратностей в массивах x и y. Число действий порядка k+l.

In [84]:
def intersection(x,y):
    result = []
    xpos=0
    ypos=0
    while xpos<len(x) and ypos<len(y):
        if x[xpos]<y[ypos]:
            xpos+=1
        elif x[xpos]>y[ypos]:  
            ypos+=1
        else:
            result.append(x[xpos])
            xpos+=1
            ypos+=1      
    return result

x = [2,2,3,4,6,6,7,8,9,9,10,10,11,16,16,17,21,24]
y = [1,2,4,4,5,8,9,9,9,10,12,16,16]
intersection(x,y)

[2, 4, 8, 9, 9, 10, 16, 16]

1.2.21. Даны два массива x[1]<=...<=x[k] и  y[1]<=...<=y[l] и число q. Найти сумму вида x[i]+y[j], наиболее близкую к числу q. (Число действий порядка k+l, дополнительная память - фиксированное число целых переменных, сами массивы менять не разрешается.)

In [ ]:
#найдем минимальное расстояние 
#между элементами двух массивов

1.2.31. Дан массив a[1..n] и число b. Переставить числа в массиве таким образом, чтобы слева от некоторой границы стояли числа, меньшие или равные b, а справа от границы — большие или равные b

In [43]:
arr = [8,12,5,6,2,1,3,9,3,8,1]
left = 0
right = len(arr)-1

def reorder(arr,l,r,pos):
    mark = arr[pos]
    while l!=r:
        if arr[l]<=mark:
            print("{}<={}".format(arr[l],mark))
            l+=1
            
        elif arr[r]>=mark:
            print("{}>={}".format(arr[r],mark))
            r-=1
            
        else:
            print("{}<-->{}".format(arr[l],arr[r]))
            arr[r],arr[l] = arr[l],arr[r]
            l+=1
            r-=1
        print(arr)

print(arr)
print()

reorder(arr,left,right,3)

print(arr)

[8, 12, 5, 6, 2, 1, 3, 9, 3, 8, 1]

8<-->1
[1, 12, 5, 6, 2, 1, 3, 9, 3, 8, 8]
8>=6
[1, 12, 5, 6, 2, 1, 3, 9, 3, 8, 8]
12<-->3
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]
5<=6
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]
6<=6
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]
2<=6
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]
1<=6
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]
3<=6
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]
[1, 3, 5, 6, 2, 1, 3, 9, 12, 8, 8]


1.2.32. Та же задача, но требуется, чтобы сначала шли элементы, меньшие b, затем равные b, а лишь затем большие b.

In [57]:
def tri_partition(arr,b):
    l=0
    m=0
    r=len(arr)-1
    
    while m!=r:
        if arr[m]==b:
            print("{}={}".format(arr[l],b))
            m+=1
        elif arr[m]>b:
            print("{}>{}".format(arr[m],b))
            arr[m],arr[r] = arr[r],arr[m]
            r-=1
        elif arr[m]<b:
            print("{}<{}".format(arr[m],b))
            arr[m],arr[l] = arr[l],arr[m]
            l+=1
            m+=1
        print(arr)
    return l,m
            
arr = [8,12,5,6,2,1,3,9,3,8,6,14]
print(arr)
tri_partition(arr,6)        

[8, 12, 5, 6, 2, 1, 3, 9, 3, 8, 6, 14]
8>6
[14, 12, 5, 6, 2, 1, 3, 9, 3, 8, 6, 8]
14>6
[6, 12, 5, 6, 2, 1, 3, 9, 3, 8, 14, 8]
6=6
[6, 12, 5, 6, 2, 1, 3, 9, 3, 8, 14, 8]
12>6
[6, 8, 5, 6, 2, 1, 3, 9, 3, 12, 14, 8]
8>6
[6, 3, 5, 6, 2, 1, 3, 9, 8, 12, 14, 8]
3<6
[3, 6, 5, 6, 2, 1, 3, 9, 8, 12, 14, 8]
5<6
[3, 5, 6, 6, 2, 1, 3, 9, 8, 12, 14, 8]
6=6
[3, 5, 6, 6, 2, 1, 3, 9, 8, 12, 14, 8]
2<6
[3, 5, 2, 6, 6, 1, 3, 9, 8, 12, 14, 8]
1<6
[3, 5, 2, 1, 6, 6, 3, 9, 8, 12, 14, 8]
3<6
[3, 5, 2, 1, 3, 6, 6, 9, 8, 12, 14, 8]


(5, 7)