"Программирование: теоремы и задачи" by А. Шень.
==

In [7]:
import numpy as np

1. Переменные, выражения, присваивания.
--

1.1.1-1.1.2 Даны две целые переменные a, b. Составить фрагмент программы,
после исполнения которого значения переменных поменялись бы местами.

In [ ]:
a = 12
b = 13

t = a
a = b
b = t
print(a,b)

In [ ]:
# python way
a,b = b,a
print(a,b)

In [ ]:
# без доп. переменных
a = a + b 
b = a - b # == a
a = a - b # == b 
print(a,b)

1.1.3-1.1.4 Дано целое число а и натуральное число n. Вычислить a^n.

In [ ]:
a = 2
n = 7

b = 1
for k in range(1,n+1):
   b = b*a
print(b)

In [ ]:
2 % 2

In [ ]:
# за C*log(n) действий
a = 2
n = 7

k = n
b = 1
c = a

print('{}^{} =={}*{}^{}'.format(a,n,b,c,k))
while k != 0:
    if n % 2 == 0:
        c = c * c
        k = k / 2
    else:
        b = b * c
        k = k - 1
    print('{}^{} =={}*{}^{}'.format(a,n,b,c,k))

1.1.7. Дано натуральное число а и целое положительное число d. Вычислить частное q и остаток r при делении а на d, не используя операций div и mod.

In [ ]:
# a = q*d + r
a = 17
d = 5

q = 0
r = a
while r >= d:
    r = r - d
    q = q + 1

print('{} =={}*{}+{}'.format(a,q,d,r)) 

1.1.8. Дано натуральное n, вычислить n! (0! = 1, n! = n · (n − 1)!).

In [ ]:
def fac(n):
    n = 5
    r = 1
    while n != 0:
        r = r * n
        n = n - 1
    return r

print(fac(4))

1.1.9 - 1.1.10 Последовательность Фибоначчи определяется так: a0 = 0, a1 =
1, ak = ak-1 + ak-2 при k2. Дано n, вычислить an.

In [ ]:
def fib(n):
    k = 2 
    a = [0,1]
    while k <= n:
        a.append( a[k-1] + a[k-2] )
        k += 1
    return a[n]

for i in range(0,9):
    print(fib(i))

In [ ]:
# за C*log(n) матричных умножений
def matrix_fib(n):
    a = np.matrix('1 1; 1 0')
    k = n
    b = np.matrix('1 0; 0 1')
    c = a
    while k != 0:
        if n % 2 == 0:
            c = c * c
            k = k / 2
        else:
            b = b * c
            k = k - 1

    return b

a = np.matrix('1 1; 1 0')
n = 7
print(a)
print(matrix_fib(n))

1.1.11 - 1.1.12 Дано натуральное n, вычислить Sum{ 1/i! } i = 0..n

In [ ]:
def smart_series_sum(n):
    k = 0 
    last = 1
    result = last
    while k < n:
        k += 1
        last = last/k
        result += last    
    return result

print(smart_series_sum(4))

1.1.20-1.1.21. Составить программу, печатающую квадраты всех натуральных чисел от 0 до заданного натурального n. Использовать из арифметических операций лишь сложение и вычитание, причем общее число действий дол- жно быть порядка n.

In [ ]:
# (k-1)^2 = k^2-2k+1 => k^2 = (k-1)^2+2k-1

def print_squares(n):
    k   = 0
    k_2 = 0
    print(k_2)
    while k != n: 
        k += 1
        k_2 = k_2 + k+k - 1
        print(k_2)

print_squares(5)

1.1.22. Составить программу, печатающую разложение на простые множители заданного натурального числа n > 0.

In [ ]:
def prime_factorization(n):
    k = 2
    i = 1
    lasting = n
    while k != n:
        if lasting % k == 0:
            print(k)
            lasting = lasting / k
        else:
            k = k+1
        i+=1
    print('{} operations'.format(i))

prime_factorization((17*2*5*7*9*13))         

In [ ]:

print(np.sqrt(17))

In [ ]:
def smart_prime_factorization(n):
    k = 2
    i = 1
    lasting = n
    while k*k < n:
        if lasting % k == 0:
            print(k)
            lasting = lasting / k
        else:
            k = k+1
        i += 1
    print('{} operations'.format(i))

smart_prime_factorization((17*2*5*7*9*13))  

1.1.26.Составить программу, печатающую десятичную запись заданного натурального числа n > 0. 

In [ ]:
def numbers(n):
    base = 1
    while 10*base < n:
        base = base * 10
    while base > 1:
        print(int(n // base))
        n = n % base
        base /= 10
    print(int(n))
        
numbers(1234)

1.1.28. Дано натуральное n. Подсчитать количество решений неравенства x^2 + y^2 < n в натуральных числах, не используя действий с вещественными числами.

In [ ]:
def solutions(n):
    x = 0
    y = 0
    

1.1.32. Дана функция f: {1...N} → {1...N}. Найти период последовательности 1,f(1),f(f(1),... Количество действий должно быть пропорционально суммарной длине предпериода и периода (эта сумма может быть существенно меньше N).

In [ ]:
periodic_func_1 = lambda k: 1 + k % 17

In [ ]:
def cycle(n,f):
    result = 1
    for i in range(1,n):
        result = f(result)
    return result

In [ ]:
for i in range(1,36):
    print(cycle(i,periodic_func_1))

In [ ]:
def find_period(f):
    k = 1
    a = f(1)
    b = f(f(1))
    while a!=b:
        k+=1
        a = f(a)
        b = f(f(b))
    
    l = 1
    b = f(a) # k+1 шаг
    while a!=b:
        l = l+1
        b = f(b)
    
    return l
    
    

find_period(periodic_func)

## 2. Массивы

1.2.5. Дан массив x: array[1..n] of integer, причем x[1]<=x[2]<=...<=x[n] Найти количество различных чисел среди элементов этого массива.

In [5]:
array = [1,1,1,2,2,3,3,4,4,5,5,5,5,5]
n = len(array)

def uniq(arr,n):
    uniq_number = 1
    for i in range(1,n):
        print(arr[i-1] != arr[i])
        if arr[i-1] != arr[i]:
            uniq_number+=1
    return uniq_number

print(uniq(array,n))
    

False
False
True
False
True
False
True
False
True
False
False
False
False
5


1.2.6. Прямоугольное поле m×n разбито на mn квадратных клеток. Некоторые клетки покрашены в чёрный цвет. Известно, что все чёрные клетки могут быть разбиты на несколько непересекающихся и не имеющих общих вершин чёрных прямоугольников. Подсчитать число чёрных прямоугольников, о которых шла речь. Число действий должно быть порядка mn.

In [24]:
random_field = np.matrix(
    '1 1 0 0; 0 0 1 1; 1 1 0 0'
)
print(random_field)

[[1 1 0 0]
 [0 0 1 1]
 [1 1 0 0]]


In [25]:
def count_black_rectangles(a):
    def is_left_corner(m,i,j):
        if a[i,j]==1:
            if i==0:
                if j==0:
                    return True
                else:
                    if a[i,j-1]==1:
                        return False
                    else:
                        return True
            else:
                if j==0:
                    if a[i-1,j]==1:
                        return False
                    else:
                        return True
                else:
                    if a[i-1,j]==1 or a[i,j-1]==1:
                        return False
                    else:
                        return True       
        else:
            return False
        
    n,m = a.shape
    
    recnum = 0
    for i in range(0,n):
        for j in range(0,m):
            if is_left_corner(a,i,j):
                recnum +=1
    return recnum
    
    
count_black_rectangles(random_field)

3